### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by MontyLoe** [JustATRIK/randomitemsmod#1]
When I type "/start (duration)" it doesn't show up as a valid command

**Comment by JustATRIK** [comment]
That's weird. Are you sure that you're using Forge as mod loader? And can you please post logs? (Can be found in ./minecraft/logs) I will help you asap :)

**Comment by JustATRIK** [comment]
Damn, I'm so sorry. I forgot to change description at Modrinth and CurseForge. Use /ri_start instead
